// Topic Service Protobuf Definitions
// Provides gRPC service for topic management — contextual knowledge entities
// richer than glossary terms but without ownership/actions/risks.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: topic.proto

package topicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Topic represents a contextual knowledge entity with keywords for auto-tagging.
type Topic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique topic identifier.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant ID for multi-tenant support.
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Topic name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Topic description (paragraph-level context, richer than glossary).
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Keywords for matching content to this topic.
	Keywords []string `protobuf:"bytes,5,rep,name=keywords,proto3" json:"keywords,omitempty"`
	// When the topic was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the topic was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_topic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{0}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Topic) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Topic) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Topic) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// TopicInput represents input for creating or updating a topic.
type TopicInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic name (required).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Topic description (optional).
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Keywords for matching content to this topic.
	Keywords      []string `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicInput) Reset() {
	*x = TopicInput{}
	mi := &file_topic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicInput) ProtoMessage() {}

func (x *TopicInput) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicInput.ProtoReflect.Descriptor instead.
func (*TopicInput) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{1}
}

func (x *TopicInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopicInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TopicInput) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

// TopicFilter contains filtering options for topic queries.
type TopicFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID (required).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Search by name (partial match).
	NameSearch string `protobuf:"bytes,2,opt,name=name_search,json=nameSearch,proto3" json:"name_search,omitempty"`
	// Filter by keyword (topics containing this keyword).
	Keyword string `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	// Maximum number of results.
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset.
	Offset        int32 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicFilter) Reset() {
	*x = TopicFilter{}
	mi := &file_topic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicFilter) ProtoMessage() {}

func (x *TopicFilter) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicFilter.ProtoReflect.Descriptor instead.
func (*TopicFilter) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{2}
}

func (x *TopicFilter) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TopicFilter) GetNameSearch() string {
	if x != nil {
		return x.NameSearch
	}
	return ""
}

func (x *TopicFilter) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *TopicFilter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TopicFilter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// CreateTopicRequest creates a new topic.
type CreateTopicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Topic input.
	Input         *TopicInput `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_topic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTopicRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTopicRequest) GetInput() *TopicInput {
	if x != nil {
		return x.Input
	}
	return nil
}

// CreateTopicResponse returns the created topic.
type CreateTopicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created topic.
	Topic         *Topic `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicResponse) Reset() {
	*x = CreateTopicResponse{}
	mi := &file_topic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicResponse) ProtoMessage() {}

func (x *CreateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicResponse.ProtoReflect.Descriptor instead.
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

// GetTopicRequest retrieves a topic.
type GetTopicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant ID.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Topic ID or name.
	Identifier    string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicRequest) Reset() {
	*x = GetTopicRequest{}
	mi := &file_topic_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicRequest) ProtoMessage() {}

func (x *GetTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicRequest.ProtoReflect.Descriptor instead.
func (*GetTopicRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopicRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTopicRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

// GetTopicResponse returns the topic.
type GetTopicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The topic.
	Topic         *Topic `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopicResponse) Reset() {
	*x = GetTopicResponse{}
	mi := &file_topic_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopicResponse) ProtoMessage() {}

func (x *GetTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopicResponse.ProtoReflect.Descriptor instead.
func (*GetTopicResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

// UpdateTopicRequest updates an existing topic.
type UpdateTopicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic ID to update.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Updated topic input.
	Input         *TopicInput `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicRequest) Reset() {
	*x = UpdateTopicRequest{}
	mi := &file_topic_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicRequest) ProtoMessage() {}

func (x *UpdateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicRequest.ProtoReflect.Descriptor instead.
func (*UpdateTopicRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTopicRequest) GetInput() *TopicInput {
	if x != nil {
		return x.Input
	}
	return nil
}

// UpdateTopicResponse returns the updated topic.
type UpdateTopicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated topic.
	Topic         *Topic `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTopicResponse) Reset() {
	*x = UpdateTopicResponse{}
	mi := &file_topic_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTopicResponse) ProtoMessage() {}

func (x *UpdateTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTopicResponse.ProtoReflect.Descriptor instead.
func (*UpdateTopicResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTopicResponse) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

// DeleteTopicRequest deletes a topic.
type DeleteTopicRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Topic ID to delete.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicRequest) Reset() {
	*x = DeleteTopicRequest{}
	mi := &file_topic_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicRequest) ProtoMessage() {}

func (x *DeleteTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicRequest.ProtoReflect.Descriptor instead.
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTopicRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteTopicResponse confirms deletion.
type DeleteTopicResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion was successful.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTopicResponse) Reset() {
	*x = DeleteTopicResponse{}
	mi := &file_topic_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTopicResponse) ProtoMessage() {}

func (x *DeleteTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTopicResponse.ProtoReflect.Descriptor instead.
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteTopicResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ListTopicsRequest lists topics.
type ListTopicsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter options.
	Filter        *TopicFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsRequest) Reset() {
	*x = ListTopicsRequest{}
	mi := &file_topic_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsRequest) ProtoMessage() {}

func (x *ListTopicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsRequest.ProtoReflect.Descriptor instead.
func (*ListTopicsRequest) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{11}
}

func (x *ListTopicsRequest) GetFilter() *TopicFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListTopicsResponse returns matching topics.
type ListTopicsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching topics.
	Topics []*Topic `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	// Total count of matching topics.
	TotalCount    int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_topic_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_topic_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_topic_proto_rawDescGZIP(), []int{12}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ListTopicsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_topic_proto protoreflect.FileDescriptor

const file_topic_proto_rawDesc = "" +
	"\n" +
	"\vtopic.proto\x12\x10penfold.topic.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfc\x01\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x05 \x03(\tR\bkeywords\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\n" +
	"TopicInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bkeywords\x18\x03 \x03(\tR\bkeywords\"\x93\x01\n" +
	"\vTopicFilter\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vname_search\x18\x02 \x01(\tR\n" +
	"nameSearch\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\"e\n" +
	"\x12CreateTopicRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x122\n" +
	"\x05input\x18\x02 \x01(\v2\x1c.penfold.topic.v1.TopicInputR\x05input\"D\n" +
	"\x13CreateTopicResponse\x12-\n" +
	"\x05topic\x18\x01 \x01(\v2\x17.penfold.topic.v1.TopicR\x05topic\"N\n" +
	"\x0fGetTopicRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\tR\n" +
	"identifier\"A\n" +
	"\x10GetTopicResponse\x12-\n" +
	"\x05topic\x18\x01 \x01(\v2\x17.penfold.topic.v1.TopicR\x05topic\"X\n" +
	"\x12UpdateTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x122\n" +
	"\x05input\x18\x02 \x01(\v2\x1c.penfold.topic.v1.TopicInputR\x05input\"D\n" +
	"\x13UpdateTopicResponse\x12-\n" +
	"\x05topic\x18\x01 \x01(\v2\x17.penfold.topic.v1.TopicR\x05topic\"$\n" +
	"\x12DeleteTopicRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"/\n" +
	"\x13DeleteTopicResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"J\n" +
	"\x11ListTopicsRequest\x125\n" +
	"\x06filter\x18\x01 \x01(\v2\x1d.penfold.topic.v1.TopicFilterR\x06filter\"f\n" +
	"\x12ListTopicsResponse\x12/\n" +
	"\x06topics\x18\x01 \x03(\v2\x17.penfold.topic.v1.TopicR\x06topics\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount2\xce\x03\n" +
	"\fTopicService\x12Z\n" +
	"\vCreateTopic\x12$.penfold.topic.v1.CreateTopicRequest\x1a%.penfold.topic.v1.CreateTopicResponse\x12Q\n" +
	"\bGetTopic\x12!.penfold.topic.v1.GetTopicRequest\x1a\".penfold.topic.v1.GetTopicResponse\x12Z\n" +
	"\vUpdateTopic\x12$.penfold.topic.v1.UpdateTopicRequest\x1a%.penfold.topic.v1.UpdateTopicResponse\x12Z\n" +
	"\vDeleteTopic\x12$.penfold.topic.v1.DeleteTopicRequest\x1a%.penfold.topic.v1.DeleteTopicResponse\x12W\n" +
	"\n" +
	"ListTopics\x12#.penfold.topic.v1.ListTopicsRequest\x1a$.penfold.topic.v1.ListTopicsResponseB@Z>github.com/otherjamesbrown/penf-cli/api/proto/topic/v1;topicv1b\x06proto3"

var (
	file_topic_proto_rawDescOnce sync.Once
	file_topic_proto_rawDescData []byte
)

func file_topic_proto_rawDescGZIP() []byte {
	file_topic_proto_rawDescOnce.Do(func() {
		file_topic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_topic_proto_rawDesc), len(file_topic_proto_rawDesc)))
	})
	return file_topic_proto_rawDescData
}

var file_topic_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_topic_proto_goTypes = []any{
	(*Topic)(nil),                 // 0: penfold.topic.v1.Topic
	(*TopicInput)(nil),            // 1: penfold.topic.v1.TopicInput
	(*TopicFilter)(nil),           // 2: penfold.topic.v1.TopicFilter
	(*CreateTopicRequest)(nil),    // 3: penfold.topic.v1.CreateTopicRequest
	(*CreateTopicResponse)(nil),   // 4: penfold.topic.v1.CreateTopicResponse
	(*GetTopicRequest)(nil),       // 5: penfold.topic.v1.GetTopicRequest
	(*GetTopicResponse)(nil),      // 6: penfold.topic.v1.GetTopicResponse
	(*UpdateTopicRequest)(nil),    // 7: penfold.topic.v1.UpdateTopicRequest
	(*UpdateTopicResponse)(nil),   // 8: penfold.topic.v1.UpdateTopicResponse
	(*DeleteTopicRequest)(nil),    // 9: penfold.topic.v1.DeleteTopicRequest
	(*DeleteTopicResponse)(nil),   // 10: penfold.topic.v1.DeleteTopicResponse
	(*ListTopicsRequest)(nil),     // 11: penfold.topic.v1.ListTopicsRequest
	(*ListTopicsResponse)(nil),    // 12: penfold.topic.v1.ListTopicsResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_topic_proto_depIdxs = []int32{
	13, // 0: penfold.topic.v1.Topic.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: penfold.topic.v1.Topic.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: penfold.topic.v1.CreateTopicRequest.input:type_name -> penfold.topic.v1.TopicInput
	0,  // 3: penfold.topic.v1.CreateTopicResponse.topic:type_name -> penfold.topic.v1.Topic
	0,  // 4: penfold.topic.v1.GetTopicResponse.topic:type_name -> penfold.topic.v1.Topic
	1,  // 5: penfold.topic.v1.UpdateTopicRequest.input:type_name -> penfold.topic.v1.TopicInput
	0,  // 6: penfold.topic.v1.UpdateTopicResponse.topic:type_name -> penfold.topic.v1.Topic
	2,  // 7: penfold.topic.v1.ListTopicsRequest.filter:type_name -> penfold.topic.v1.TopicFilter
	0,  // 8: penfold.topic.v1.ListTopicsResponse.topics:type_name -> penfold.topic.v1.Topic
	3,  // 9: penfold.topic.v1.TopicService.CreateTopic:input_type -> penfold.topic.v1.CreateTopicRequest
	5,  // 10: penfold.topic.v1.TopicService.GetTopic:input_type -> penfold.topic.v1.GetTopicRequest
	7,  // 11: penfold.topic.v1.TopicService.UpdateTopic:input_type -> penfold.topic.v1.UpdateTopicRequest
	9,  // 12: penfold.topic.v1.TopicService.DeleteTopic:input_type -> penfold.topic.v1.DeleteTopicRequest
	11, // 13: penfold.topic.v1.TopicService.ListTopics:input_type -> penfold.topic.v1.ListTopicsRequest
	4,  // 14: penfold.topic.v1.TopicService.CreateTopic:output_type -> penfold.topic.v1.CreateTopicResponse
	6,  // 15: penfold.topic.v1.TopicService.GetTopic:output_type -> penfold.topic.v1.GetTopicResponse
	8,  // 16: penfold.topic.v1.TopicService.UpdateTopic:output_type -> penfold.topic.v1.UpdateTopicResponse
	10, // 17: penfold.topic.v1.TopicService.DeleteTopic:output_type -> penfold.topic.v1.DeleteTopicResponse
	12, // 18: penfold.topic.v1.TopicService.ListTopics:output_type -> penfold.topic.v1.ListTopicsResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_topic_proto_init() }
func file_topic_proto_init() {
	if File_topic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_topic_proto_rawDesc), len(file_topic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_topic_proto_goTypes,
		DependencyIndexes: file_topic_proto_depIdxs,
		MessageInfos:      file_topic_proto_msgTypes,
	}.Build()
	File_topic_proto = out.File
	file_topic_proto_goTypes = nil
	file_topic_proto_depIdxs = nil
}
