// Schedule Service Protobuf Definitions
// Provides gRPC service for DB-driven schedule management — cron, interval, heartbeat jobs.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/schedule/v1/schedule.proto

package schedulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScheduleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CronExpr       string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	WorkflowType   string                 `protobuf:"bytes,6,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	WorkflowParams string                 `protobuf:"bytes,7,opt,name=workflow_params,json=workflowParams,proto3" json:"workflow_params,omitempty"`
	OverlapPolicy  string                 `protobuf:"bytes,8,opt,name=overlap_policy,json=overlapPolicy,proto3" json:"overlap_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScheduleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateScheduleRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateScheduleRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *CreateScheduleRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *CreateScheduleRequest) GetWorkflowParams() string {
	if x != nil {
		return x.WorkflowParams
	}
	return ""
}

func (x *CreateScheduleRequest) GetOverlapPolicy() string {
	if x != nil {
		return x.OverlapPolicy
	}
	return ""
}

type CreateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId    string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleResponse) Reset() {
	*x = CreateScheduleResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleResponse) ProtoMessage() {}

func (x *CreateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{1}
}

func (x *CreateScheduleResponse) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type UpdateScheduleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScheduleId     string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CronExpr       string                 `protobuf:"bytes,4,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	WorkflowType   string                 `protobuf:"bytes,5,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	WorkflowParams string                 `protobuf:"bytes,6,opt,name=workflow_params,json=workflowParams,proto3" json:"workflow_params,omitempty"`
	OverlapPolicy  string                 `protobuf:"bytes,7,opt,name=overlap_policy,json=overlapPolicy,proto3" json:"overlap_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateScheduleRequest) Reset() {
	*x = UpdateScheduleRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleRequest) ProtoMessage() {}

func (x *UpdateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleRequest.ProtoReflect.Descriptor instead.
func (*UpdateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateScheduleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *UpdateScheduleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateScheduleRequest) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *UpdateScheduleRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *UpdateScheduleRequest) GetWorkflowParams() string {
	if x != nil {
		return x.WorkflowParams
	}
	return ""
}

func (x *UpdateScheduleRequest) GetOverlapPolicy() string {
	if x != nil {
		return x.OverlapPolicy
	}
	return ""
}

type UpdateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScheduleResponse) Reset() {
	*x = UpdateScheduleResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScheduleResponse) ProtoMessage() {}

func (x *UpdateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScheduleResponse.ProtoReflect.Descriptor instead.
func (*UpdateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{3}
}

type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteScheduleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type DeleteScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleResponse) Reset() {
	*x = DeleteScheduleResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleResponse) ProtoMessage() {}

func (x *DeleteScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{5}
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{6}
}

func (x *ListSchedulesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListSchedulesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSchedulesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleSummary     `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{7}
}

func (x *ListSchedulesResponse) GetSchedules() []*ScheduleSummary {
	if x != nil {
		return x.Schedules
	}
	return nil
}

func (x *ListSchedulesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ScheduleSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type           string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CronExpr       string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr,omitempty"`
	WorkflowType   string                 `protobuf:"bytes,6,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Enabled        bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	OverlapPolicy  string                 `protobuf:"bytes,8,opt,name=overlap_policy,json=overlapPolicy,proto3" json:"overlap_policy,omitempty"`
	LastStatus     string                 `protobuf:"bytes,9,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"`
	LastRunAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`
	NextRunAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	LastError      string                 `protobuf:"bytes,12,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	WorkflowParams string                 `protobuf:"bytes,13,opt,name=workflow_params,json=workflowParams,proto3" json:"workflow_params,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleSummary) Reset() {
	*x = ScheduleSummary{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleSummary) ProtoMessage() {}

func (x *ScheduleSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleSummary.ProtoReflect.Descriptor instead.
func (*ScheduleSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{8}
}

func (x *ScheduleSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScheduleSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleSummary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ScheduleSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScheduleSummary) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *ScheduleSummary) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *ScheduleSummary) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ScheduleSummary) GetOverlapPolicy() string {
	if x != nil {
		return x.OverlapPolicy
	}
	return ""
}

func (x *ScheduleSummary) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *ScheduleSummary) GetLastRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRunAt
	}
	return nil
}

func (x *ScheduleSummary) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *ScheduleSummary) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *ScheduleSummary) GetWorkflowParams() string {
	if x != nil {
		return x.WorkflowParams
	}
	return ""
}

type PauseScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleRequest) Reset() {
	*x = PauseScheduleRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleRequest) ProtoMessage() {}

func (x *PauseScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleRequest.ProtoReflect.Descriptor instead.
func (*PauseScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{9}
}

func (x *PauseScheduleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PauseScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type PauseScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleResponse) Reset() {
	*x = PauseScheduleResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleResponse) ProtoMessage() {}

func (x *PauseScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleResponse.ProtoReflect.Descriptor instead.
func (*PauseScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{10}
}

type ResumeScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScheduleRequest) Reset() {
	*x = ResumeScheduleRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScheduleRequest) ProtoMessage() {}

func (x *ResumeScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScheduleRequest.ProtoReflect.Descriptor instead.
func (*ResumeScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{11}
}

func (x *ResumeScheduleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResumeScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

type ResumeScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeScheduleResponse) Reset() {
	*x = ResumeScheduleResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeScheduleResponse) ProtoMessage() {}

func (x *ResumeScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeScheduleResponse.ProtoReflect.Descriptor instead.
func (*ResumeScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{12}
}

type GetScheduleHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleHistoryRequest) Reset() {
	*x = GetScheduleHistoryRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleHistoryRequest) ProtoMessage() {}

func (x *GetScheduleHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetScheduleHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{13}
}

func (x *GetScheduleHistoryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetScheduleHistoryRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *GetScheduleHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetScheduleHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Executions    []*ScheduleExecution   `protobuf:"bytes,1,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScheduleHistoryResponse) Reset() {
	*x = GetScheduleHistoryResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScheduleHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScheduleHistoryResponse) ProtoMessage() {}

func (x *GetScheduleHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScheduleHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetScheduleHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{14}
}

func (x *GetScheduleHistoryResponse) GetExecutions() []*ScheduleExecution {
	if x != nil {
		return x.Executions
	}
	return nil
}

type ScheduleExecution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScheduleId     string                 `protobuf:"bytes,1,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	WorkflowRunId  string                 `protobuf:"bytes,6,opt,name=workflow_run_id,json=workflowRunId,proto3" json:"workflow_run_id,omitempty"`
	ResultMetadata string                 `protobuf:"bytes,7,opt,name=result_metadata,json=resultMetadata,proto3" json:"result_metadata,omitempty"` // JSON string with execution result details
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ScheduleExecution) Reset() {
	*x = ScheduleExecution{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleExecution) ProtoMessage() {}

func (x *ScheduleExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleExecution.ProtoReflect.Descriptor instead.
func (*ScheduleExecution) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{15}
}

func (x *ScheduleExecution) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *ScheduleExecution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduleExecution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ScheduleExecution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ScheduleExecution) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScheduleExecution) GetWorkflowRunId() string {
	if x != nil {
		return x.WorkflowRunId
	}
	return ""
}

func (x *ScheduleExecution) GetResultMetadata() string {
	if x != nil {
		return x.ResultMetadata
	}
	return ""
}

type TriggerScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	ReferenceDate *string                `protobuf:"bytes,3,opt,name=reference_date,json=referenceDate,proto3,oneof" json:"reference_date,omitempty"` // YYYY-MM-DD date simulation, default: today
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScheduleRequest) Reset() {
	*x = TriggerScheduleRequest{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduleRequest) ProtoMessage() {}

func (x *TriggerScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduleRequest.ProtoReflect.Descriptor instead.
func (*TriggerScheduleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{16}
}

func (x *TriggerScheduleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TriggerScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *TriggerScheduleRequest) GetReferenceDate() string {
	if x != nil && x.ReferenceDate != nil {
		return *x.ReferenceDate
	}
	return ""
}

type TriggerScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerScheduleResponse) Reset() {
	*x = TriggerScheduleResponse{}
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerScheduleResponse) ProtoMessage() {}

func (x *TriggerScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_schedule_v1_schedule_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerScheduleResponse.ProtoReflect.Descriptor instead.
func (*TriggerScheduleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_schedule_v1_schedule_proto_rawDescGZIP(), []int{17}
}

var File_api_proto_schedule_v1_schedule_proto protoreflect.FileDescriptor

const file_api_proto_schedule_v1_schedule_proto_rawDesc = "" +
	"\n" +
	"$api/proto/schedule/v1/schedule.proto\x12\x13penfold.schedule.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x02\n" +
	"\x15CreateScheduleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12#\n" +
	"\rworkflow_type\x18\x06 \x01(\tR\fworkflowType\x12'\n" +
	"\x0fworkflow_params\x18\a \x01(\tR\x0eworkflowParams\x12%\n" +
	"\x0eoverlap_policy\x18\b \x01(\tR\roverlapPolicy\"9\n" +
	"\x16CreateScheduleResponse\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\"\x89\x02\n" +
	"\x15UpdateScheduleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tcron_expr\x18\x04 \x01(\tR\bcronExpr\x12#\n" +
	"\rworkflow_type\x18\x05 \x01(\tR\fworkflowType\x12'\n" +
	"\x0fworkflow_params\x18\x06 \x01(\tR\x0eworkflowParams\x12%\n" +
	"\x0eoverlap_policy\x18\a \x01(\tR\roverlapPolicy\"\x18\n" +
	"\x16UpdateScheduleResponse\"U\n" +
	"\x15DeleteScheduleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\"\x18\n" +
	"\x16DeleteScheduleResponse\"a\n" +
	"\x14ListSchedulesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"|\n" +
	"\x15ListSchedulesResponse\x12B\n" +
	"\tschedules\x18\x01 \x03(\v2$.penfold.schedule.v1.ScheduleSummaryR\tschedules\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xcf\x03\n" +
	"\x0fScheduleSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12#\n" +
	"\rworkflow_type\x18\x06 \x01(\tR\fworkflowType\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x12%\n" +
	"\x0eoverlap_policy\x18\b \x01(\tR\roverlapPolicy\x12\x1f\n" +
	"\vlast_status\x18\t \x01(\tR\n" +
	"lastStatus\x12:\n" +
	"\vlast_run_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tlastRunAt\x12:\n" +
	"\vnext_run_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\f \x01(\tR\tlastError\x12'\n" +
	"\x0fworkflow_params\x18\r \x01(\tR\x0eworkflowParams\"T\n" +
	"\x14PauseScheduleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\"\x17\n" +
	"\x15PauseScheduleResponse\"U\n" +
	"\x15ResumeScheduleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\"\x18\n" +
	"\x16ResumeScheduleResponse\"o\n" +
	"\x19GetScheduleHistoryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"d\n" +
	"\x1aGetScheduleHistoryResponse\x12F\n" +
	"\n" +
	"executions\x18\x01 \x03(\v2&.penfold.schedule.v1.ScheduleExecutionR\n" +
	"executions\"\xad\x02\n" +
	"\x11ScheduleExecution\x12\x1f\n" +
	"\vschedule_id\x18\x01 \x01(\tR\n" +
	"scheduleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12&\n" +
	"\x0fworkflow_run_id\x18\x06 \x01(\tR\rworkflowRunId\x12'\n" +
	"\x0fresult_metadata\x18\a \x01(\tR\x0eresultMetadata\"\x95\x01\n" +
	"\x16TriggerScheduleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12*\n" +
	"\x0ereference_date\x18\x03 \x01(\tH\x00R\rreferenceDate\x88\x01\x01B\x11\n" +
	"\x0f_reference_date\"\x19\n" +
	"\x17TriggerScheduleResponse2\xf2\x06\n" +
	"\x0fScheduleService\x12i\n" +
	"\x0eCreateSchedule\x12*.penfold.schedule.v1.CreateScheduleRequest\x1a+.penfold.schedule.v1.CreateScheduleResponse\x12i\n" +
	"\x0eUpdateSchedule\x12*.penfold.schedule.v1.UpdateScheduleRequest\x1a+.penfold.schedule.v1.UpdateScheduleResponse\x12i\n" +
	"\x0eDeleteSchedule\x12*.penfold.schedule.v1.DeleteScheduleRequest\x1a+.penfold.schedule.v1.DeleteScheduleResponse\x12f\n" +
	"\rListSchedules\x12).penfold.schedule.v1.ListSchedulesRequest\x1a*.penfold.schedule.v1.ListSchedulesResponse\x12f\n" +
	"\rPauseSchedule\x12).penfold.schedule.v1.PauseScheduleRequest\x1a*.penfold.schedule.v1.PauseScheduleResponse\x12i\n" +
	"\x0eResumeSchedule\x12*.penfold.schedule.v1.ResumeScheduleRequest\x1a+.penfold.schedule.v1.ResumeScheduleResponse\x12u\n" +
	"\x12GetScheduleHistory\x12..penfold.schedule.v1.GetScheduleHistoryRequest\x1a/.penfold.schedule.v1.GetScheduleHistoryResponse\x12l\n" +
	"\x0fTriggerSchedule\x12+.penfold.schedule.v1.TriggerScheduleRequest\x1a,.penfold.schedule.v1.TriggerScheduleResponseBFZDgithub.com/otherjamesbrown/penf-cli/api/proto/schedule/v1;schedulev1b\x06proto3"

var (
	file_api_proto_schedule_v1_schedule_proto_rawDescOnce sync.Once
	file_api_proto_schedule_v1_schedule_proto_rawDescData []byte
)

func file_api_proto_schedule_v1_schedule_proto_rawDescGZIP() []byte {
	file_api_proto_schedule_v1_schedule_proto_rawDescOnce.Do(func() {
		file_api_proto_schedule_v1_schedule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_schedule_v1_schedule_proto_rawDesc), len(file_api_proto_schedule_v1_schedule_proto_rawDesc)))
	})
	return file_api_proto_schedule_v1_schedule_proto_rawDescData
}

var file_api_proto_schedule_v1_schedule_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_schedule_v1_schedule_proto_goTypes = []any{
	(*CreateScheduleRequest)(nil),      // 0: penfold.schedule.v1.CreateScheduleRequest
	(*CreateScheduleResponse)(nil),     // 1: penfold.schedule.v1.CreateScheduleResponse
	(*UpdateScheduleRequest)(nil),      // 2: penfold.schedule.v1.UpdateScheduleRequest
	(*UpdateScheduleResponse)(nil),     // 3: penfold.schedule.v1.UpdateScheduleResponse
	(*DeleteScheduleRequest)(nil),      // 4: penfold.schedule.v1.DeleteScheduleRequest
	(*DeleteScheduleResponse)(nil),     // 5: penfold.schedule.v1.DeleteScheduleResponse
	(*ListSchedulesRequest)(nil),       // 6: penfold.schedule.v1.ListSchedulesRequest
	(*ListSchedulesResponse)(nil),      // 7: penfold.schedule.v1.ListSchedulesResponse
	(*ScheduleSummary)(nil),            // 8: penfold.schedule.v1.ScheduleSummary
	(*PauseScheduleRequest)(nil),       // 9: penfold.schedule.v1.PauseScheduleRequest
	(*PauseScheduleResponse)(nil),      // 10: penfold.schedule.v1.PauseScheduleResponse
	(*ResumeScheduleRequest)(nil),      // 11: penfold.schedule.v1.ResumeScheduleRequest
	(*ResumeScheduleResponse)(nil),     // 12: penfold.schedule.v1.ResumeScheduleResponse
	(*GetScheduleHistoryRequest)(nil),  // 13: penfold.schedule.v1.GetScheduleHistoryRequest
	(*GetScheduleHistoryResponse)(nil), // 14: penfold.schedule.v1.GetScheduleHistoryResponse
	(*ScheduleExecution)(nil),          // 15: penfold.schedule.v1.ScheduleExecution
	(*TriggerScheduleRequest)(nil),     // 16: penfold.schedule.v1.TriggerScheduleRequest
	(*TriggerScheduleResponse)(nil),    // 17: penfold.schedule.v1.TriggerScheduleResponse
	(*timestamppb.Timestamp)(nil),      // 18: google.protobuf.Timestamp
}
var file_api_proto_schedule_v1_schedule_proto_depIdxs = []int32{
	8,  // 0: penfold.schedule.v1.ListSchedulesResponse.schedules:type_name -> penfold.schedule.v1.ScheduleSummary
	18, // 1: penfold.schedule.v1.ScheduleSummary.last_run_at:type_name -> google.protobuf.Timestamp
	18, // 2: penfold.schedule.v1.ScheduleSummary.next_run_at:type_name -> google.protobuf.Timestamp
	15, // 3: penfold.schedule.v1.GetScheduleHistoryResponse.executions:type_name -> penfold.schedule.v1.ScheduleExecution
	18, // 4: penfold.schedule.v1.ScheduleExecution.started_at:type_name -> google.protobuf.Timestamp
	18, // 5: penfold.schedule.v1.ScheduleExecution.completed_at:type_name -> google.protobuf.Timestamp
	0,  // 6: penfold.schedule.v1.ScheduleService.CreateSchedule:input_type -> penfold.schedule.v1.CreateScheduleRequest
	2,  // 7: penfold.schedule.v1.ScheduleService.UpdateSchedule:input_type -> penfold.schedule.v1.UpdateScheduleRequest
	4,  // 8: penfold.schedule.v1.ScheduleService.DeleteSchedule:input_type -> penfold.schedule.v1.DeleteScheduleRequest
	6,  // 9: penfold.schedule.v1.ScheduleService.ListSchedules:input_type -> penfold.schedule.v1.ListSchedulesRequest
	9,  // 10: penfold.schedule.v1.ScheduleService.PauseSchedule:input_type -> penfold.schedule.v1.PauseScheduleRequest
	11, // 11: penfold.schedule.v1.ScheduleService.ResumeSchedule:input_type -> penfold.schedule.v1.ResumeScheduleRequest
	13, // 12: penfold.schedule.v1.ScheduleService.GetScheduleHistory:input_type -> penfold.schedule.v1.GetScheduleHistoryRequest
	16, // 13: penfold.schedule.v1.ScheduleService.TriggerSchedule:input_type -> penfold.schedule.v1.TriggerScheduleRequest
	1,  // 14: penfold.schedule.v1.ScheduleService.CreateSchedule:output_type -> penfold.schedule.v1.CreateScheduleResponse
	3,  // 15: penfold.schedule.v1.ScheduleService.UpdateSchedule:output_type -> penfold.schedule.v1.UpdateScheduleResponse
	5,  // 16: penfold.schedule.v1.ScheduleService.DeleteSchedule:output_type -> penfold.schedule.v1.DeleteScheduleResponse
	7,  // 17: penfold.schedule.v1.ScheduleService.ListSchedules:output_type -> penfold.schedule.v1.ListSchedulesResponse
	10, // 18: penfold.schedule.v1.ScheduleService.PauseSchedule:output_type -> penfold.schedule.v1.PauseScheduleResponse
	12, // 19: penfold.schedule.v1.ScheduleService.ResumeSchedule:output_type -> penfold.schedule.v1.ResumeScheduleResponse
	14, // 20: penfold.schedule.v1.ScheduleService.GetScheduleHistory:output_type -> penfold.schedule.v1.GetScheduleHistoryResponse
	17, // 21: penfold.schedule.v1.ScheduleService.TriggerSchedule:output_type -> penfold.schedule.v1.TriggerScheduleResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_schedule_v1_schedule_proto_init() }
func file_api_proto_schedule_v1_schedule_proto_init() {
	if File_api_proto_schedule_v1_schedule_proto != nil {
		return
	}
	file_api_proto_schedule_v1_schedule_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_schedule_v1_schedule_proto_rawDesc), len(file_api_proto_schedule_v1_schedule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_schedule_v1_schedule_proto_goTypes,
		DependencyIndexes: file_api_proto_schedule_v1_schedule_proto_depIdxs,
		MessageInfos:      file_api_proto_schedule_v1_schedule_proto_msgTypes,
	}.Build()
	File_api_proto_schedule_v1_schedule_proto = out.File
	file_api_proto_schedule_v1_schedule_proto_goTypes = nil
	file_api_proto_schedule_v1_schedule_proto_depIdxs = nil
}
