// Ledger Service Protobuf Definitions
// Provides gRPC service for the session ledger — narrative context capture across sessions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ledger/v1/ledger.proto

package ledgerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntryType classifies what kind of narrative record this is.
type EntryType int32

const (
	EntryType_ENTRY_TYPE_UNSPECIFIED EntryType = 0
	EntryType_ENTRY_TYPE_NARRATIVE   EntryType = 1 // Context, reasoning, background
	EntryType_ENTRY_TYPE_DECISION    EntryType = 2 // Choice made with rationale
	EntryType_ENTRY_TYPE_DISCOVERY   EntryType = 3 // Finding, insight, root cause
	EntryType_ENTRY_TYPE_HANDOFF     EntryType = 4 // Session state for resumption
	EntryType_ENTRY_TYPE_ACTIVITY    EntryType = 5 // System operation (search, entity lookup, etc.)
)

// Enum value maps for EntryType.
var (
	EntryType_name = map[int32]string{
		0: "ENTRY_TYPE_UNSPECIFIED",
		1: "ENTRY_TYPE_NARRATIVE",
		2: "ENTRY_TYPE_DECISION",
		3: "ENTRY_TYPE_DISCOVERY",
		4: "ENTRY_TYPE_HANDOFF",
		5: "ENTRY_TYPE_ACTIVITY",
	}
	EntryType_value = map[string]int32{
		"ENTRY_TYPE_UNSPECIFIED": 0,
		"ENTRY_TYPE_NARRATIVE":   1,
		"ENTRY_TYPE_DECISION":    2,
		"ENTRY_TYPE_DISCOVERY":   3,
		"ENTRY_TYPE_HANDOFF":     4,
		"ENTRY_TYPE_ACTIVITY":    5,
	}
)

func (x EntryType) Enum() *EntryType {
	p := new(EntryType)
	*p = x
	return p
}

func (x EntryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryType) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_ledger_proto_enumTypes[0].Descriptor()
}

func (EntryType) Type() protoreflect.EnumType {
	return &file_ledger_v1_ledger_proto_enumTypes[0]
}

func (x EntryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryType.Descriptor instead.
func (EntryType) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

// EntrySource tracks which system generated the entry.
type EntrySource int32

const (
	EntrySource_ENTRY_SOURCE_UNSPECIFIED EntrySource = 0
	EntrySource_ENTRY_SOURCE_PENF        EntrySource = 1 // Generated from penf CLI operations
	EntrySource_ENTRY_SOURCE_CXP         EntrySource = 2 // Generated from cxp operations
	EntrySource_ENTRY_SOURCE_MANUAL      EntrySource = 3 // Manually created by agent or user
)

// Enum value maps for EntrySource.
var (
	EntrySource_name = map[int32]string{
		0: "ENTRY_SOURCE_UNSPECIFIED",
		1: "ENTRY_SOURCE_PENF",
		2: "ENTRY_SOURCE_CXP",
		3: "ENTRY_SOURCE_MANUAL",
	}
	EntrySource_value = map[string]int32{
		"ENTRY_SOURCE_UNSPECIFIED": 0,
		"ENTRY_SOURCE_PENF":        1,
		"ENTRY_SOURCE_CXP":         2,
		"ENTRY_SOURCE_MANUAL":      3,
	}
)

func (x EntrySource) Enum() *EntrySource {
	p := new(EntrySource)
	*p = x
	return p
}

func (x EntrySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntrySource) Descriptor() protoreflect.EnumDescriptor {
	return file_ledger_v1_ledger_proto_enumTypes[1].Descriptor()
}

func (EntrySource) Type() protoreflect.EnumType {
	return &file_ledger_v1_ledger_proto_enumTypes[1]
}

func (x EntrySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntrySource.Descriptor instead.
func (EntrySource) EnumDescriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

// LedgerEntry is an immutable narrative record.
type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EntryType     EntryType              `protobuf:"varint,4,opt,name=entry_type,json=entryType,proto3,enum=penfold.ledger.v1.EntryType" json:"entry_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Body          *string                `protobuf:"bytes,6,opt,name=body,proto3,oneof" json:"body,omitempty"`
	Source        EntrySource            `protobuf:"varint,7,opt,name=source,proto3,enum=penfold.ledger.v1.EntrySource" json:"source,omitempty"`
	Agent         string                 `protobuf:"bytes,8,opt,name=agent,proto3" json:"agent,omitempty"`
	Labels        []string               `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty"`
	ShardRefs     []string               `protobuf:"bytes,10,rep,name=shard_refs,json=shardRefs,proto3" json:"shard_refs,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *LedgerEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LedgerEntry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LedgerEntry) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LedgerEntry) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *LedgerEntry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LedgerEntry) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *LedgerEntry) GetSource() EntrySource {
	if x != nil {
		return x.Source
	}
	return EntrySource_ENTRY_SOURCE_UNSPECIFIED
}

func (x *LedgerEntry) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *LedgerEntry) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *LedgerEntry) GetShardRefs() []string {
	if x != nil {
		return x.ShardRefs
	}
	return nil
}

func (x *LedgerEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *LedgerEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SessionSummary is an aggregated view of a session's entries.
type SessionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Agent         string                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	EntryCount    int32                  `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	FirstEntry    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=first_entry,json=firstEntry,proto3" json:"first_entry,omitempty"`
	LastEntry     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_entry,json=lastEntry,proto3" json:"last_entry,omitempty"`
	EntryTypes    []string               `protobuf:"bytes,6,rep,name=entry_types,json=entryTypes,proto3" json:"entry_types,omitempty"`          // Distinct types present
	Labels        []string               `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty"`                                    // Aggregated labels
	LatestTitle   *string                `protobuf:"bytes,8,opt,name=latest_title,json=latestTitle,proto3,oneof" json:"latest_title,omitempty"` // Title of most recent entry
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSummary) Reset() {
	*x = SessionSummary{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSummary) ProtoMessage() {}

func (x *SessionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSummary.ProtoReflect.Descriptor instead.
func (*SessionSummary) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *SessionSummary) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionSummary) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SessionSummary) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *SessionSummary) GetFirstEntry() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstEntry
	}
	return nil
}

func (x *SessionSummary) GetLastEntry() *timestamppb.Timestamp {
	if x != nil {
		return x.LastEntry
	}
	return nil
}

func (x *SessionSummary) GetEntryTypes() []string {
	if x != nil {
		return x.EntryTypes
	}
	return nil
}

func (x *SessionSummary) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SessionSummary) GetLatestTitle() string {
	if x != nil && x.LatestTitle != nil {
		return *x.LatestTitle
	}
	return ""
}

// Consolidation is an LLM-generated summary of ledger entries.
type Consolidation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Title          string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body           string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	SourceEntryIds []int64                `protobuf:"varint,5,rep,packed,name=source_entry_ids,json=sourceEntryIds,proto3" json:"source_entry_ids,omitempty"`
	SessionIds     []string               `protobuf:"bytes,6,rep,name=session_ids,json=sessionIds,proto3" json:"session_ids,omitempty"`
	Decisions      []*Decision            `protobuf:"bytes,7,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Patterns       []*Pattern             `protobuf:"bytes,8,rep,name=patterns,proto3" json:"patterns,omitempty"`
	TimeStart      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=time_start,json=timeStart,proto3" json:"time_start,omitempty"`
	TimeEnd        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=time_end,json=timeEnd,proto3" json:"time_end,omitempty"`
	ModelId        *string                `protobuf:"bytes,11,opt,name=model_id,json=modelId,proto3,oneof" json:"model_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Consolidation) Reset() {
	*x = Consolidation{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consolidation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consolidation) ProtoMessage() {}

func (x *Consolidation) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consolidation.ProtoReflect.Descriptor instead.
func (*Consolidation) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Consolidation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Consolidation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Consolidation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Consolidation) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Consolidation) GetSourceEntryIds() []int64 {
	if x != nil {
		return x.SourceEntryIds
	}
	return nil
}

func (x *Consolidation) GetSessionIds() []string {
	if x != nil {
		return x.SessionIds
	}
	return nil
}

func (x *Consolidation) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *Consolidation) GetPatterns() []*Pattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *Consolidation) GetTimeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeStart
	}
	return nil
}

func (x *Consolidation) GetTimeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeEnd
	}
	return nil
}

func (x *Consolidation) GetModelId() string {
	if x != nil && x.ModelId != nil {
		return *x.ModelId
	}
	return ""
}

func (x *Consolidation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Decision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *Decision) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Decision) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Decision) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Pattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Evidence      []string               `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"` // Entry IDs or session IDs supporting this
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pattern) Reset() {
	*x = Pattern{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pattern) ProtoMessage() {}

func (x *Pattern) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pattern.ProtoReflect.Descriptor instead.
func (*Pattern) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *Pattern) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Pattern) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Pattern) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type CreateEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EntryType     EntryType              `protobuf:"varint,3,opt,name=entry_type,json=entryType,proto3,enum=penfold.ledger.v1.EntryType" json:"entry_type,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body          *string                `protobuf:"bytes,5,opt,name=body,proto3,oneof" json:"body,omitempty"`
	Source        EntrySource            `protobuf:"varint,6,opt,name=source,proto3,enum=penfold.ledger.v1.EntrySource" json:"source,omitempty"`
	Agent         string                 `protobuf:"bytes,7,opt,name=agent,proto3" json:"agent,omitempty"`
	Labels        []string               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`
	ShardRefs     []string               `protobuf:"bytes,9,rep,name=shard_refs,json=shardRefs,proto3" json:"shard_refs,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryRequest) Reset() {
	*x = CreateEntryRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryRequest) ProtoMessage() {}

func (x *CreateEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryRequest.ProtoReflect.Descriptor instead.
func (*CreateEntryRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEntryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateEntryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateEntryRequest) GetEntryType() EntryType {
	if x != nil {
		return x.EntryType
	}
	return EntryType_ENTRY_TYPE_UNSPECIFIED
}

func (x *CreateEntryRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateEntryRequest) GetBody() string {
	if x != nil && x.Body != nil {
		return *x.Body
	}
	return ""
}

func (x *CreateEntryRequest) GetSource() EntrySource {
	if x != nil {
		return x.Source
	}
	return EntrySource_ENTRY_SOURCE_UNSPECIFIED
}

func (x *CreateEntryRequest) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *CreateEntryRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateEntryRequest) GetShardRefs() []string {
	if x != nil {
		return x.ShardRefs
	}
	return nil
}

func (x *CreateEntryRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *LedgerEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEntryResponse) Reset() {
	*x = CreateEntryResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEntryResponse) ProtoMessage() {}

func (x *CreateEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEntryResponse.ProtoReflect.Descriptor instead.
func (*CreateEntryResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEntryResponse) GetEntry() *LedgerEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type GetEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntryRequest) Reset() {
	*x = GetEntryRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntryRequest) ProtoMessage() {}

func (x *GetEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntryRequest.ProtoReflect.Descriptor instead.
func (*GetEntryRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *GetEntryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetEntryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     *string                `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"` // Filter by session
	EntryType     *string                `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3,oneof" json:"entry_type,omitempty"` // Filter by type
	Source        *string                `protobuf:"bytes,4,opt,name=source,proto3,oneof" json:"source,omitempty"`                        // Filter by source
	Agent         *string                `protobuf:"bytes,5,opt,name=agent,proto3,oneof" json:"agent,omitempty"`                          // Filter by agent
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`                              // Filter by labels (AND)
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *ListEntriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListEntriesRequest) GetSessionId() string {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return ""
}

func (x *ListEntriesRequest) GetEntryType() string {
	if x != nil && x.EntryType != nil {
		return *x.EntryType
	}
	return ""
}

func (x *ListEntriesRequest) GetSource() string {
	if x != nil && x.Source != nil {
		return *x.Source
	}
	return ""
}

func (x *ListEntriesRequest) GetAgent() string {
	if x != nil && x.Agent != nil {
		return *x.Agent
	}
	return ""
}

func (x *ListEntriesRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{9}
}

func (x *ListEntriesResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Agent         *string                `protobuf:"bytes,2,opt,name=agent,proto3,oneof" json:"agent,omitempty"` // Filter by agent
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{10}
}

func (x *ListSessionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListSessionsRequest) GetAgent() string {
	if x != nil && x.Agent != nil {
		return *x.Agent
	}
	return ""
}

func (x *ListSessionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSessionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionSummary      `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsResponse) GetSessions() []*SessionSummary {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *ListSessionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{12}
}

func (x *GetSessionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *SessionSummary        `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Entries       []*LedgerEntry         `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{13}
}

func (x *GetSessionResponse) GetSummary() *SessionSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetSessionResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SearchEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"` // Full-text search query
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEntriesRequest) Reset() {
	*x = SearchEntriesRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntriesRequest) ProtoMessage() {}

func (x *SearchEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntriesRequest.ProtoReflect.Descriptor instead.
func (*SearchEntriesRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{14}
}

func (x *SearchEntriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchEntriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchEntriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEntriesResponse) Reset() {
	*x = SearchEntriesResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEntriesResponse) ProtoMessage() {}

func (x *SearchEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEntriesResponse.ProtoReflect.Descriptor instead.
func (*SearchEntriesResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{15}
}

func (x *SearchEntriesResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *SearchEntriesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetLatestHandoffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Agent         *string                `protobuf:"bytes,2,opt,name=agent,proto3,oneof" json:"agent,omitempty"` // Filter by agent (default: any)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestHandoffRequest) Reset() {
	*x = GetLatestHandoffRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestHandoffRequest) ProtoMessage() {}

func (x *GetLatestHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestHandoffRequest.ProtoReflect.Descriptor instead.
func (*GetLatestHandoffRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{16}
}

func (x *GetLatestHandoffRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetLatestHandoffRequest) GetAgent() string {
	if x != nil && x.Agent != nil {
		return *x.Agent
	}
	return ""
}

type ListConsolidationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsolidationsRequest) Reset() {
	*x = ListConsolidationsRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationsRequest) ProtoMessage() {}

func (x *ListConsolidationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationsRequest.ProtoReflect.Descriptor instead.
func (*ListConsolidationsRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{17}
}

func (x *ListConsolidationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListConsolidationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListConsolidationsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListConsolidationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Consolidations []*Consolidation       `protobuf:"bytes,1,rep,name=consolidations,proto3" json:"consolidations,omitempty"`
	Total          int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListConsolidationsResponse) Reset() {
	*x = ListConsolidationsResponse{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsolidationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsolidationsResponse) ProtoMessage() {}

func (x *ListConsolidationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsolidationsResponse.ProtoReflect.Descriptor instead.
func (*ListConsolidationsResponse) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{18}
}

func (x *ListConsolidationsResponse) GetConsolidations() []*Consolidation {
	if x != nil {
		return x.Consolidations
	}
	return nil
}

func (x *ListConsolidationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetConsolidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConsolidationRequest) Reset() {
	*x = GetConsolidationRequest{}
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConsolidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsolidationRequest) ProtoMessage() {}

func (x *GetConsolidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_v1_ledger_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsolidationRequest.ProtoReflect.Descriptor instead.
func (*GetConsolidationRequest) Descriptor() ([]byte, []int) {
	return file_ledger_v1_ledger_proto_rawDescGZIP(), []int{19}
}

func (x *GetConsolidationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetConsolidationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_ledger_v1_ledger_proto protoreflect.FileDescriptor

const file_ledger_v1_ledger_proto_rawDesc = "" +
	"\n" +
	"\x16ledger/v1/ledger.proto\x12\x11penfold.ledger.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x04\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12;\n" +
	"\n" +
	"entry_type\x18\x04 \x01(\x0e2\x1c.penfold.ledger.v1.EntryTypeR\tentryType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x17\n" +
	"\x04body\x18\x06 \x01(\tH\x00R\x04body\x88\x01\x01\x126\n" +
	"\x06source\x18\a \x01(\x0e2\x1e.penfold.ledger.v1.EntrySourceR\x06source\x12\x14\n" +
	"\x05agent\x18\b \x01(\tR\x05agent\x12\x16\n" +
	"\x06labels\x18\t \x03(\tR\x06labels\x12\x1d\n" +
	"\n" +
	"shard_refs\x18\n" +
	" \x03(\tR\tshardRefs\x12H\n" +
	"\bmetadata\x18\v \x03(\v2,.penfold.ledger.v1.LedgerEntry.MetadataEntryR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_body\"\xd0\x02\n" +
	"\x0eSessionSummary\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05agent\x18\x02 \x01(\tR\x05agent\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x05R\n" +
	"entryCount\x12;\n" +
	"\vfirst_entry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"firstEntry\x129\n" +
	"\n" +
	"last_entry\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tlastEntry\x12\x1f\n" +
	"\ventry_types\x18\x06 \x03(\tR\n" +
	"entryTypes\x12\x16\n" +
	"\x06labels\x18\a \x03(\tR\x06labels\x12&\n" +
	"\flatest_title\x18\b \x01(\tH\x00R\vlatestTitle\x88\x01\x01B\x0f\n" +
	"\r_latest_title\"\xfe\x03\n" +
	"\rConsolidation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12(\n" +
	"\x10source_entry_ids\x18\x05 \x03(\x03R\x0esourceEntryIds\x12\x1f\n" +
	"\vsession_ids\x18\x06 \x03(\tR\n" +
	"sessionIds\x129\n" +
	"\tdecisions\x18\a \x03(\v2\x1b.penfold.ledger.v1.DecisionR\tdecisions\x126\n" +
	"\bpatterns\x18\b \x03(\v2\x1a.penfold.ledger.v1.PatternR\bpatterns\x129\n" +
	"\n" +
	"time_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimeStart\x125\n" +
	"\btime_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\atimeEnd\x12\x1e\n" +
	"\bmodel_id\x18\v \x01(\tH\x00R\amodelId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\v\n" +
	"\t_model_id\"S\n" +
	"\bDecision\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"O\n" +
	"\aPattern\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x1a\n" +
	"\bevidence\x18\x03 \x03(\tR\bevidence\"\xd8\x03\n" +
	"\x12CreateEntryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12;\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\x0e2\x1c.penfold.ledger.v1.EntryTypeR\tentryType\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x17\n" +
	"\x04body\x18\x05 \x01(\tH\x00R\x04body\x88\x01\x01\x126\n" +
	"\x06source\x18\x06 \x01(\x0e2\x1e.penfold.ledger.v1.EntrySourceR\x06source\x12\x14\n" +
	"\x05agent\x18\a \x01(\tR\x05agent\x12\x16\n" +
	"\x06labels\x18\b \x03(\tR\x06labels\x12\x1d\n" +
	"\n" +
	"shard_refs\x18\t \x03(\tR\tshardRefs\x12O\n" +
	"\bmetadata\x18\n" +
	" \x03(\v23.penfold.ledger.v1.CreateEntryRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_body\"K\n" +
	"\x13CreateEntryResponse\x124\n" +
	"\x05entry\x18\x01 \x01(\v2\x1e.penfold.ledger.v1.LedgerEntryR\x05entry\">\n" +
	"\x0fGetEntryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\xaa\x02\n" +
	"\x12ListEntriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tH\x00R\tsessionId\x88\x01\x01\x12\"\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tH\x01R\tentryType\x88\x01\x01\x12\x1b\n" +
	"\x06source\x18\x04 \x01(\tH\x02R\x06source\x88\x01\x01\x12\x19\n" +
	"\x05agent\x18\x05 \x01(\tH\x03R\x05agent\x88\x01\x01\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\b \x01(\x05R\x06offsetB\r\n" +
	"\v_session_idB\r\n" +
	"\v_entry_typeB\t\n" +
	"\a_sourceB\b\n" +
	"\x06_agent\"e\n" +
	"\x13ListEntriesResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.penfold.ledger.v1.LedgerEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x85\x01\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\x05agent\x18\x02 \x01(\tH\x00R\x05agent\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offsetB\b\n" +
	"\x06_agent\"k\n" +
	"\x14ListSessionsResponse\x12=\n" +
	"\bsessions\x18\x01 \x03(\v2!.penfold.ledger.v1.SessionSummaryR\bsessions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"O\n" +
	"\x11GetSessionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x8b\x01\n" +
	"\x12GetSessionResponse\x12;\n" +
	"\asummary\x18\x01 \x01(\v2!.penfold.ledger.v1.SessionSummaryR\asummary\x128\n" +
	"\aentries\x18\x02 \x03(\v2\x1e.penfold.ledger.v1.LedgerEntryR\aentries\"w\n" +
	"\x14SearchEntriesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"g\n" +
	"\x15SearchEntriesResponse\x128\n" +
	"\aentries\x18\x01 \x03(\v2\x1e.penfold.ledger.v1.LedgerEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"[\n" +
	"\x17GetLatestHandoffRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\x05agent\x18\x02 \x01(\tH\x00R\x05agent\x88\x01\x01B\b\n" +
	"\x06_agent\"f\n" +
	"\x19ListConsolidationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"|\n" +
	"\x1aListConsolidationsResponse\x12H\n" +
	"\x0econsolidations\x18\x01 \x03(\v2 .penfold.ledger.v1.ConsolidationR\x0econsolidations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x17GetConsolidationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id*\xa5\x01\n" +
	"\tEntryType\x12\x1a\n" +
	"\x16ENTRY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ENTRY_TYPE_NARRATIVE\x10\x01\x12\x17\n" +
	"\x13ENTRY_TYPE_DECISION\x10\x02\x12\x18\n" +
	"\x14ENTRY_TYPE_DISCOVERY\x10\x03\x12\x16\n" +
	"\x12ENTRY_TYPE_HANDOFF\x10\x04\x12\x17\n" +
	"\x13ENTRY_TYPE_ACTIVITY\x10\x05*q\n" +
	"\vEntrySource\x12\x1c\n" +
	"\x18ENTRY_SOURCE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ENTRY_SOURCE_PENF\x10\x01\x12\x14\n" +
	"\x10ENTRY_SOURCE_CXP\x10\x02\x12\x17\n" +
	"\x13ENTRY_SOURCE_MANUAL\x10\x032\xf0\x06\n" +
	"\rLedgerService\x12\\\n" +
	"\vCreateEntry\x12%.penfold.ledger.v1.CreateEntryRequest\x1a&.penfold.ledger.v1.CreateEntryResponse\x12N\n" +
	"\bGetEntry\x12\".penfold.ledger.v1.GetEntryRequest\x1a\x1e.penfold.ledger.v1.LedgerEntry\x12\\\n" +
	"\vListEntries\x12%.penfold.ledger.v1.ListEntriesRequest\x1a&.penfold.ledger.v1.ListEntriesResponse\x12_\n" +
	"\fListSessions\x12&.penfold.ledger.v1.ListSessionsRequest\x1a'.penfold.ledger.v1.ListSessionsResponse\x12Y\n" +
	"\n" +
	"GetSession\x12$.penfold.ledger.v1.GetSessionRequest\x1a%.penfold.ledger.v1.GetSessionResponse\x12b\n" +
	"\rSearchEntries\x12'.penfold.ledger.v1.SearchEntriesRequest\x1a(.penfold.ledger.v1.SearchEntriesResponse\x12^\n" +
	"\x10GetLatestHandoff\x12*.penfold.ledger.v1.GetLatestHandoffRequest\x1a\x1e.penfold.ledger.v1.LedgerEntry\x12q\n" +
	"\x12ListConsolidations\x12,.penfold.ledger.v1.ListConsolidationsRequest\x1a-.penfold.ledger.v1.ListConsolidationsResponse\x12`\n" +
	"\x10GetConsolidation\x12*.penfold.ledger.v1.GetConsolidationRequest\x1a .penfold.ledger.v1.ConsolidationBBZ@github.com/otherjamesbrown/penf-cli/api/proto/ledger/v1;ledgerv1b\x06proto3"

var (
	file_ledger_v1_ledger_proto_rawDescOnce sync.Once
	file_ledger_v1_ledger_proto_rawDescData []byte
)

func file_ledger_v1_ledger_proto_rawDescGZIP() []byte {
	file_ledger_v1_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_v1_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)))
	})
	return file_ledger_v1_ledger_proto_rawDescData
}

var file_ledger_v1_ledger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ledger_v1_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ledger_v1_ledger_proto_goTypes = []any{
	(EntryType)(0),                     // 0: penfold.ledger.v1.EntryType
	(EntrySource)(0),                   // 1: penfold.ledger.v1.EntrySource
	(*LedgerEntry)(nil),                // 2: penfold.ledger.v1.LedgerEntry
	(*SessionSummary)(nil),             // 3: penfold.ledger.v1.SessionSummary
	(*Consolidation)(nil),              // 4: penfold.ledger.v1.Consolidation
	(*Decision)(nil),                   // 5: penfold.ledger.v1.Decision
	(*Pattern)(nil),                    // 6: penfold.ledger.v1.Pattern
	(*CreateEntryRequest)(nil),         // 7: penfold.ledger.v1.CreateEntryRequest
	(*CreateEntryResponse)(nil),        // 8: penfold.ledger.v1.CreateEntryResponse
	(*GetEntryRequest)(nil),            // 9: penfold.ledger.v1.GetEntryRequest
	(*ListEntriesRequest)(nil),         // 10: penfold.ledger.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),        // 11: penfold.ledger.v1.ListEntriesResponse
	(*ListSessionsRequest)(nil),        // 12: penfold.ledger.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),       // 13: penfold.ledger.v1.ListSessionsResponse
	(*GetSessionRequest)(nil),          // 14: penfold.ledger.v1.GetSessionRequest
	(*GetSessionResponse)(nil),         // 15: penfold.ledger.v1.GetSessionResponse
	(*SearchEntriesRequest)(nil),       // 16: penfold.ledger.v1.SearchEntriesRequest
	(*SearchEntriesResponse)(nil),      // 17: penfold.ledger.v1.SearchEntriesResponse
	(*GetLatestHandoffRequest)(nil),    // 18: penfold.ledger.v1.GetLatestHandoffRequest
	(*ListConsolidationsRequest)(nil),  // 19: penfold.ledger.v1.ListConsolidationsRequest
	(*ListConsolidationsResponse)(nil), // 20: penfold.ledger.v1.ListConsolidationsResponse
	(*GetConsolidationRequest)(nil),    // 21: penfold.ledger.v1.GetConsolidationRequest
	nil,                                // 22: penfold.ledger.v1.LedgerEntry.MetadataEntry
	nil,                                // 23: penfold.ledger.v1.CreateEntryRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),      // 24: google.protobuf.Timestamp
}
var file_ledger_v1_ledger_proto_depIdxs = []int32{
	0,  // 0: penfold.ledger.v1.LedgerEntry.entry_type:type_name -> penfold.ledger.v1.EntryType
	1,  // 1: penfold.ledger.v1.LedgerEntry.source:type_name -> penfold.ledger.v1.EntrySource
	22, // 2: penfold.ledger.v1.LedgerEntry.metadata:type_name -> penfold.ledger.v1.LedgerEntry.MetadataEntry
	24, // 3: penfold.ledger.v1.LedgerEntry.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: penfold.ledger.v1.SessionSummary.first_entry:type_name -> google.protobuf.Timestamp
	24, // 5: penfold.ledger.v1.SessionSummary.last_entry:type_name -> google.protobuf.Timestamp
	5,  // 6: penfold.ledger.v1.Consolidation.decisions:type_name -> penfold.ledger.v1.Decision
	6,  // 7: penfold.ledger.v1.Consolidation.patterns:type_name -> penfold.ledger.v1.Pattern
	24, // 8: penfold.ledger.v1.Consolidation.time_start:type_name -> google.protobuf.Timestamp
	24, // 9: penfold.ledger.v1.Consolidation.time_end:type_name -> google.protobuf.Timestamp
	24, // 10: penfold.ledger.v1.Consolidation.created_at:type_name -> google.protobuf.Timestamp
	0,  // 11: penfold.ledger.v1.CreateEntryRequest.entry_type:type_name -> penfold.ledger.v1.EntryType
	1,  // 12: penfold.ledger.v1.CreateEntryRequest.source:type_name -> penfold.ledger.v1.EntrySource
	23, // 13: penfold.ledger.v1.CreateEntryRequest.metadata:type_name -> penfold.ledger.v1.CreateEntryRequest.MetadataEntry
	2,  // 14: penfold.ledger.v1.CreateEntryResponse.entry:type_name -> penfold.ledger.v1.LedgerEntry
	2,  // 15: penfold.ledger.v1.ListEntriesResponse.entries:type_name -> penfold.ledger.v1.LedgerEntry
	3,  // 16: penfold.ledger.v1.ListSessionsResponse.sessions:type_name -> penfold.ledger.v1.SessionSummary
	3,  // 17: penfold.ledger.v1.GetSessionResponse.summary:type_name -> penfold.ledger.v1.SessionSummary
	2,  // 18: penfold.ledger.v1.GetSessionResponse.entries:type_name -> penfold.ledger.v1.LedgerEntry
	2,  // 19: penfold.ledger.v1.SearchEntriesResponse.entries:type_name -> penfold.ledger.v1.LedgerEntry
	4,  // 20: penfold.ledger.v1.ListConsolidationsResponse.consolidations:type_name -> penfold.ledger.v1.Consolidation
	7,  // 21: penfold.ledger.v1.LedgerService.CreateEntry:input_type -> penfold.ledger.v1.CreateEntryRequest
	9,  // 22: penfold.ledger.v1.LedgerService.GetEntry:input_type -> penfold.ledger.v1.GetEntryRequest
	10, // 23: penfold.ledger.v1.LedgerService.ListEntries:input_type -> penfold.ledger.v1.ListEntriesRequest
	12, // 24: penfold.ledger.v1.LedgerService.ListSessions:input_type -> penfold.ledger.v1.ListSessionsRequest
	14, // 25: penfold.ledger.v1.LedgerService.GetSession:input_type -> penfold.ledger.v1.GetSessionRequest
	16, // 26: penfold.ledger.v1.LedgerService.SearchEntries:input_type -> penfold.ledger.v1.SearchEntriesRequest
	18, // 27: penfold.ledger.v1.LedgerService.GetLatestHandoff:input_type -> penfold.ledger.v1.GetLatestHandoffRequest
	19, // 28: penfold.ledger.v1.LedgerService.ListConsolidations:input_type -> penfold.ledger.v1.ListConsolidationsRequest
	21, // 29: penfold.ledger.v1.LedgerService.GetConsolidation:input_type -> penfold.ledger.v1.GetConsolidationRequest
	8,  // 30: penfold.ledger.v1.LedgerService.CreateEntry:output_type -> penfold.ledger.v1.CreateEntryResponse
	2,  // 31: penfold.ledger.v1.LedgerService.GetEntry:output_type -> penfold.ledger.v1.LedgerEntry
	11, // 32: penfold.ledger.v1.LedgerService.ListEntries:output_type -> penfold.ledger.v1.ListEntriesResponse
	13, // 33: penfold.ledger.v1.LedgerService.ListSessions:output_type -> penfold.ledger.v1.ListSessionsResponse
	15, // 34: penfold.ledger.v1.LedgerService.GetSession:output_type -> penfold.ledger.v1.GetSessionResponse
	17, // 35: penfold.ledger.v1.LedgerService.SearchEntries:output_type -> penfold.ledger.v1.SearchEntriesResponse
	2,  // 36: penfold.ledger.v1.LedgerService.GetLatestHandoff:output_type -> penfold.ledger.v1.LedgerEntry
	20, // 37: penfold.ledger.v1.LedgerService.ListConsolidations:output_type -> penfold.ledger.v1.ListConsolidationsResponse
	4,  // 38: penfold.ledger.v1.LedgerService.GetConsolidation:output_type -> penfold.ledger.v1.Consolidation
	30, // [30:39] is the sub-list for method output_type
	21, // [21:30] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_ledger_v1_ledger_proto_init() }
func file_ledger_v1_ledger_proto_init() {
	if File_ledger_v1_ledger_proto != nil {
		return
	}
	file_ledger_v1_ledger_proto_msgTypes[0].OneofWrappers = []any{}
	file_ledger_v1_ledger_proto_msgTypes[1].OneofWrappers = []any{}
	file_ledger_v1_ledger_proto_msgTypes[2].OneofWrappers = []any{}
	file_ledger_v1_ledger_proto_msgTypes[5].OneofWrappers = []any{}
	file_ledger_v1_ledger_proto_msgTypes[8].OneofWrappers = []any{}
	file_ledger_v1_ledger_proto_msgTypes[10].OneofWrappers = []any{}
	file_ledger_v1_ledger_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_v1_ledger_proto_rawDesc), len(file_ledger_v1_ledger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_v1_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_v1_ledger_proto_depIdxs,
		EnumInfos:         file_ledger_v1_ledger_proto_enumTypes,
		MessageInfos:      file_ledger_v1_ledger_proto_msgTypes,
	}.Build()
	File_ledger_v1_ledger_proto = out.File
	file_ledger_v1_ledger_proto_goTypes = nil
	file_ledger_v1_ledger_proto_depIdxs = nil
}
