package cmd

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	digestv1 "github.com/otherjamesbrown/penf-cli/api/proto/digest/v1"
	"github.com/otherjamesbrown/penf-cli/config"
)

var (
	digestOutput  string
	digestProject string
	digestDate    string
	digestSince   string
	digestUntil   string
	digestType    string
	digestLimit   int
	digestFocus   string
)

// DigestCommandDeps holds dependencies for digest commands.
type DigestCommandDeps struct {
	Config     *config.CLIConfig
	LoadConfig func() (*config.CLIConfig, error)
}

// DefaultDigestDeps returns the default dependencies.
func DefaultDigestDeps() *DigestCommandDeps {
	return &DigestCommandDeps{
		LoadConfig: config.LoadConfig,
	}
}

// NewDigestCommand creates the root digest command with all subcommands.
func NewDigestCommand(deps *DigestCommandDeps) *cobra.Command {
	if deps == nil {
		deps = DefaultDigestDeps()
	}

	cmd := &cobra.Command{
		Use:   "digest",
		Short: "Manage project digests — automated daily/weekly summaries",
		Long: `Digests are automated narrative summaries of project activity. A daily digest
aggregates attributed content, extracted assertions, instruction matches, and
session ledger entries into a structured summary generated by the LLM.`,
		Aliases: []string{"digests"},
	}

	cmd.PersistentFlags().StringVarP(&digestOutput, "output", "o", "", "Output format: text, json, yaml")

	cmd.AddCommand(newDigestGenerateCommand(deps))
	cmd.AddCommand(newDigestShowCommand(deps))
	cmd.AddCommand(newDigestLatestCommand(deps))
	cmd.AddCommand(newDigestListCommand(deps))

	return cmd
}

// ==================== Generate ====================

func newDigestGenerateCommand(deps *DigestCommandDeps) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "generate <project>",
		Short: "Trigger digest generation for a project",
		Long: `Generate a digest for a project. Supports daily, weekly, and journal types.
Daily and weekly digests are idempotent — if a digest already exists for the date, it is returned.
Journal entries are always new and can be directed by a --focus question.`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDigestGenerate(cmd.Context(), deps, args[0])
		},
	}

	cmd.Flags().StringVar(&digestDate, "date", "", "Date for digest generation (YYYY-MM-DD, default: today)")
	cmd.Flags().StringVar(&digestType, "type", "daily", "Digest type: daily, weekly, journal")
	cmd.Flags().StringVar(&digestFocus, "focus", "", "Focus question for journal entries")

	return cmd
}

func runDigestGenerate(ctx context.Context, deps *DigestCommandDeps, project string) error {
	cfg, err := deps.LoadConfig()
	if err != nil {
		return fmt.Errorf("loading configuration: %w", err)
	}
	deps.Config = cfg

	conn, err := connectToGateway(cfg)
	if err != nil {
		return fmt.Errorf("connecting to gateway: %w", err)
	}
	defer conn.Close()

	client := digestv1.NewDigestServiceClient(conn)

	tenantID, err := resolveTenantID(deps.Config)
	if err != nil {
		return err
	}

	date := digestDate
	if date == "" {
		date = time.Now().Format("2006-01-02")
	}

	resp, err := client.TriggerDigest(ctx, &digestv1.TriggerDigestRequest{
		TenantId:    tenantID,
		ProjectName: project,
		Date:        date,
		DigestType:  digestType,
		Focus:       digestFocus,
	})
	if err != nil {
		return fmt.Errorf("triggering digest: %w", err)
	}

	format := resolveOutputFormat(digestOutput, cfg)

	if resp.AlreadyExists {
		switch format {
		case config.OutputFormatJSON:
			out := map[string]interface{}{
				"already_exists": true,
				"digest_id":     resp.DigestId,
			}
			data, _ := json.MarshalIndent(out, "", "  ")
			fmt.Println(string(data))
		case config.OutputFormatYAML:
			out := map[string]interface{}{
				"already_exists": true,
				"digest_id":     resp.DigestId,
			}
			data, _ := yaml.Marshal(out)
			fmt.Print(string(data))
		default:
			fmt.Printf("Digest already exists for %s on %s (id: %s)\n", project, date, resp.DigestId)
		}
		return nil
	}

	switch format {
	case config.OutputFormatJSON:
		out := map[string]interface{}{
			"workflow_id": resp.WorkflowId,
			"project":     project,
			"date":        date,
		}
		data, _ := json.MarshalIndent(out, "", "  ")
		fmt.Println(string(data))
	case config.OutputFormatYAML:
		out := map[string]interface{}{
			"workflow_id": resp.WorkflowId,
			"project":     project,
			"date":        date,
		}
		data, _ := yaml.Marshal(out)
		fmt.Print(string(data))
	default:
		fmt.Printf("Digest generation started for %s on %s (workflow: %s)\n", project, date, resp.WorkflowId)
	}
	return nil
}

// ==================== Show ====================

func newDigestShowCommand(deps *DigestCommandDeps) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show <digest-id>",
		Short: "Show details of a specific digest",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDigestShow(cmd.Context(), deps, args[0])
		},
	}
	return cmd
}

func runDigestShow(ctx context.Context, deps *DigestCommandDeps, digestID string) error {
	cfg, err := deps.LoadConfig()
	if err != nil {
		return fmt.Errorf("loading configuration: %w", err)
	}
	deps.Config = cfg

	conn, err := connectToGateway(cfg)
	if err != nil {
		return fmt.Errorf("connecting to gateway: %w", err)
	}
	defer conn.Close()

	client := digestv1.NewDigestServiceClient(conn)

	tenantID, err := resolveTenantID(deps.Config)
	if err != nil {
		return err
	}

	resp, err := client.GetDigest(ctx, &digestv1.GetDigestRequest{
		TenantId: tenantID,
		DigestId: digestID,
	})
	if err != nil {
		return fmt.Errorf("getting digest: %w", err)
	}

	outputDigestDetail(resp.Digest, resolveOutputFormat(digestOutput, cfg))
	return nil
}

// ==================== Latest ====================

func newDigestLatestCommand(deps *DigestCommandDeps) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "latest <project>",
		Short: "Show the most recent digest for a project",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDigestLatest(cmd.Context(), deps, args[0])
		},
	}

	cmd.Flags().StringVar(&digestType, "type", "daily", "Digest type: daily, weekly, journal")

	return cmd
}

func runDigestLatest(ctx context.Context, deps *DigestCommandDeps, project string) error {
	cfg, err := deps.LoadConfig()
	if err != nil {
		return fmt.Errorf("loading configuration: %w", err)
	}
	deps.Config = cfg

	conn, err := connectToGateway(cfg)
	if err != nil {
		return fmt.Errorf("connecting to gateway: %w", err)
	}
	defer conn.Close()

	client := digestv1.NewDigestServiceClient(conn)

	tenantID, err := resolveTenantID(deps.Config)
	if err != nil {
		return err
	}

	resp, err := client.GetLatestDigest(ctx, &digestv1.GetLatestDigestRequest{
		TenantId:    tenantID,
		ProjectName: project,
		DigestType:  digestType,
	})
	if err != nil {
		return fmt.Errorf("getting latest digest: %w", err)
	}

	outputDigestDetail(resp.Digest, resolveOutputFormat(digestOutput, cfg))
	return nil
}

// ==================== List ====================

func newDigestListCommand(deps *DigestCommandDeps) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List digests for a project",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runDigestList(cmd.Context(), deps)
		},
	}

	cmd.Flags().StringVar(&digestProject, "project", "", "Project name (required)")
	cmd.Flags().StringVar(&digestSince, "since", "", "Start date (YYYY-MM-DD)")
	cmd.Flags().StringVar(&digestUntil, "until", "", "End date (YYYY-MM-DD)")
	cmd.Flags().StringVar(&digestType, "type", "", "Filter by digest type")
	cmd.Flags().IntVar(&digestLimit, "limit", 20, "Maximum results")

	_ = cmd.MarkFlagRequired("project")

	return cmd
}

func runDigestList(ctx context.Context, deps *DigestCommandDeps) error {
	cfg, err := deps.LoadConfig()
	if err != nil {
		return fmt.Errorf("loading configuration: %w", err)
	}
	deps.Config = cfg

	conn, err := connectToGateway(cfg)
	if err != nil {
		return fmt.Errorf("connecting to gateway: %w", err)
	}
	defer conn.Close()

	client := digestv1.NewDigestServiceClient(conn)

	tenantID, err := resolveTenantID(deps.Config)
	if err != nil {
		return err
	}

	resp, err := client.ListDigests(ctx, &digestv1.ListDigestsRequest{
		TenantId:    tenantID,
		ProjectName: digestProject,
		Since:       digestSince,
		Until:       digestUntil,
		DigestType:  digestType,
		Limit:       int32(digestLimit),
	})
	if err != nil {
		return fmt.Errorf("listing digests: %w", err)
	}

	format := resolveOutputFormat(digestOutput, cfg)

	switch format {
	case config.OutputFormatJSON:
		items := make([]map[string]interface{}, len(resp.Digests))
		for i, d := range resp.Digests {
			items[i] = map[string]interface{}{
				"id":           d.Id,
				"project_id":   d.ProjectId,
				"project_name": d.ProjectName,
				"digest_type":  d.DigestType,
				"period_start": d.PeriodStart,
				"period_end":   d.PeriodEnd,
				"created_at":   d.CreatedAt,
			}
		}
		data, _ := json.MarshalIndent(items, "", "  ")
		fmt.Println(string(data))
	case config.OutputFormatYAML:
		items := make([]map[string]interface{}, len(resp.Digests))
		for i, d := range resp.Digests {
			items[i] = map[string]interface{}{
				"id":           d.Id,
				"project_name": d.ProjectName,
				"digest_type":  d.DigestType,
				"period_start": d.PeriodStart,
				"created_at":   d.CreatedAt,
			}
		}
		data, _ := yaml.Marshal(items)
		fmt.Print(string(data))
	default:
		if len(resp.Digests) == 0 {
			fmt.Println("No digests found.")
			return nil
		}
		fmt.Printf("%-16s %-8s %-12s %-20s %s\n", "ID", "TYPE", "PERIOD", "PROJECT", "CREATED")
		for _, d := range resp.Digests {
			fmt.Printf("%-16s %-8s %-12s %-20s %s\n",
				truncateString(d.Id, 16),
				d.DigestType,
				d.PeriodStart,
				truncateString(d.ProjectName, 20),
				d.CreatedAt,
			)
		}
	}
	return nil
}

// ==================== Helpers ====================

func outputDigestDetail(d *digestv1.DigestDetail, format config.OutputFormat) {
	if d == nil {
		fmt.Println("No digest found.")
		return
	}

	switch format {
	case config.OutputFormatJSON:
		out := map[string]interface{}{
			"id":                 d.Id,
			"tenant_id":         d.TenantId,
			"project_id":        d.ProjectId,
			"project_name":      d.ProjectName,
			"digest_type":       d.DigestType,
			"period_start":      d.PeriodStart,
			"period_end":        d.PeriodEnd,
			"body":              json.RawMessage(d.Body),
			"model_used":        d.ModelUsed,
			"input_token_count":  d.InputTokenCount,
			"output_token_count": d.OutputTokenCount,
			"created_at":        d.CreatedAt,
		}
		data, _ := json.MarshalIndent(out, "", "  ")
		fmt.Println(string(data))
	case config.OutputFormatYAML:
		out := map[string]interface{}{
			"id":           d.Id,
			"project_name": d.ProjectName,
			"digest_type":  d.DigestType,
			"period_start": d.PeriodStart,
			"period_end":   d.PeriodEnd,
			"body":         d.Body,
			"model_used":   d.ModelUsed,
			"created_at":   d.CreatedAt,
		}
		data, _ := yaml.Marshal(out)
		fmt.Print(string(data))
	default:
		fmt.Printf("Digest: %s\n", d.Id)
		fmt.Printf("  Project:  %s (id: %d)\n", d.ProjectName, d.ProjectId)
		fmt.Printf("  Type:     %s\n", d.DigestType)
		fmt.Printf("  Period:   %s to %s\n", d.PeriodStart, d.PeriodEnd)
		fmt.Printf("  Model:    %s\n", d.ModelUsed)
		fmt.Printf("  Tokens:   %d in / %d out\n", d.InputTokenCount, d.OutputTokenCount)
		fmt.Printf("  Created:  %s\n", d.CreatedAt)
		fmt.Println()
		// Pretty-print the body JSON
		var bodyParsed interface{}
		if err := json.Unmarshal([]byte(d.Body), &bodyParsed); err == nil {
			prettyBody, _ := json.MarshalIndent(bodyParsed, "  ", "  ")
			fmt.Printf("  Body:\n  %s\n", string(prettyBody))
		} else {
			fmt.Printf("  Body: %s\n", d.Body)
		}
	}
}

